before_script:
  - cp config/database.peak_flow.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:schema:load RAILS_ENV=test
  - curl -sSf https://lets.tunshell.com/init.sh | sh -s -- T U9OcUl4iGkkpsm3zJhmcm5 J4Ccg4ukbrjdUUPnSP46uR eu.relay.tunshell.com
environment:
  REDIS_URL: redis://redis:6379/0
rvm: true
script:
  - bundle exec rspec
  - bundle exec rubocop
services:
  postgres:
    environment:
      POSTGRES_USER: "peakflow"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "peakflow_test"
    expose:
      - 5432
    image: postgres:11.4
  redis:
    image: redis:5.0.7
    expose:
      - 6379
